library(Gviz)
#options(ucscChromosomeNames=FALSE)
alTrack <- AlignmentsTrack("Sorted/SRR493366Aligned.sortedByCoord.out.bam",isPaired=T,background.title ="#042E8A",col="#042E8A",fill="#042E8A",size=0.04,fontsize=16,showTitle=FALSE)
#grtrack <- GeneRegionTrack("/group/bioi1/shared/projects/superTranscript/reference_generation/Homo_sapiens.GRCh37.71.primary_assembly.protein_coding.exongene.gtf",chromsome="16",name="Transcripts",transcriptAnnotation="transcript",size=0.5,background.title ="#619CFF",fill="#619CFF",col="black")
grtrack <- GeneRegionTrack("/group/bioi1/shared/genomes/hg19/star/hg19_gencodeV19_comp.gtf",chromsome="16",name="Transcripts",transcriptAnnotation="transcript",size=0.5,background.title ="#619CFF",fill="#619CFF",col="black",fontsize=16)
gtrack <- GenomeAxisTrack()
pdf('coverage_ref.pdf',width=15,height=6)
plotTracks(list(gtrack,alTrack,grtrack),from=67062000,to=67135000,chromosome="16",type=c("coverage"))
dev.off()
